services:
  - type: web
    name: ikramzafar-portfolio
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    pullRequestPreviewsEnabled: true

